---
apiVersion: v1
kind: Namespace
metadata:
  name: car-rental-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend-deployment
  namespace: car-rental-ns
  labels:
    app: angular-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-container
          image: repo12.azurecr.io/angular-image:v1.0
          ports:
            - containerPort: 80
      # Uncomment if not using managed identity
      # imagePullSecrets:
      #   - name: acr-auth-secret

---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: car-rental-ns
spec:
  type: ClusterIP
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-frontend-ingress
  namespace: car-rental-ns
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: gscncmhgeah9ccbz.fz26.alb.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-frontend-service
                port:
                  number: 80
