# Stage 1: Build Angular App
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install --frozen-lockfile

COPY . .
RUN npm run build --configuration=production

# Stage 2: NGINX Server
FROM nginx:alpine

# Remove default web content
RUN rm -rf /usr/share/nginx/html/*

# Copy built Angular app
COPY --from=builder /app/dist/car-rental-angular/browser /usr/share/nginx/html

# Use your custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
